Run: ButtonGame.class
	java --module-path ../javafx/lib --add-modules javafx.controls ButtonGame

ButtonGame.class: ButtonGame.java
	javac --module-path ../javafx/lib --add-modules javafx.controls ButtonGame.java
