Run: FirstJavaFX.class
	java --module-path ../javafx/lib --add-modules javafx.controls FirstJavaFX

FirstJavaFX.class: FirstJavaFX.java
	javac --module-path ../javafx/lib --add-modules javafx.controls FirstJavaFX.java
